#!/usr/bin/env python3
"""
Split CSV and Run Pyrmind Helper

This script helps you:
1. Split a large CSV file into smaller files by distributing rows evenly across N folders
2. Create a folder for each split
3. Optionally start pyrmind to process all folders in parallel

Usage:
    python split_and_run.py
    python split_and_run.py --csv data.csv --num-folders 10
"""

import csv
import os
import sys
import subprocess
import argparse
import math


def find_csv_files():
    """Find CSV files in current directory."""
    csv_files = [f for f in os.listdir('.') if f.endswith('.csv') and os.path.isfile(f)]
    return csv_files


def select_csv_file():
    """Let user select a CSV file to process."""
    csv_files = find_csv_files()
    
    if not csv_files:
        print("No CSV files found in current directory.")
        print("Please run this script from the directory containing your CSV file.")
        sys.exit(1)
    
    if len(csv_files) == 1:
        print(f"Found: {csv_files[0]}")
        return csv_files[0]
    
    print("\nAvailable CSV files:")
    for i, f in enumerate(csv_files, 1):
        print(f"  {i}. {f}")
    
    while True:
        choice = input("\nSelect file number (or enter path): ").strip()
        if not choice:
            continue
        
        if choice.isdigit():
            idx = int(choice) - 1
            if 0 <= idx < len(csv_files):
                return csv_files[idx]
            print(f"Please enter 1-{len(csv_files)}")
            continue
        
        if os.path.isfile(choice):
            return choice
        
        print(f"File not found: {choice}")


def select_num_folders():
    """Ask user how many folders to create."""
    while True:
        choice = input("\nNumber of folders to create: ").strip()
        if not choice:
            continue
        try:
            num = int(choice)
            if num > 0:
                return num
            print("Please enter a positive number")
        except ValueError:
            print("Please enter a valid number")


def select_output_base():
    """Let user specify or confirm output base directory."""
    default = "processed"
    
    choice = input(f"\nOutput directory name [{default}]: ").strip()
    return choice if choice else default


def select_mode():
    """Let user choose between interactive and direct mode."""
    print("\n" + "=" * 50)
    print("EXECUTION MODE")
    print("=" * 50)
    print("""
1. INTERACTIVE MODE
   - Split CSV into folders
   - WAIT for you to press Enter
   - You can check folder contents in another terminal
   - Then press Enter to start processing

2. DIRECT MODE  
   - Split CSV into folders
   - START pyrmind immediately
   - Monitor with 'pyrmind attach' in another terminal

3. SPLIT ONLY
   - Just split the CSV
   - Don't start pyrmind
   - You run it manually later
""")
    
    while True:
        choice = input("Select mode (1/2/3) [1]: ").strip() or "1"
        if choice in ('1', '2', '3'):
            return choice
        print("Please enter 1, 2, or 3")


def split_by_num_folders(csv_path, num_folders, output_base):
    """Split CSV evenly into N folders."""
    print(f"\nReading {csv_path}...")
    
    rows = []
    fieldnames = []
    
    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        
        for row in reader:
            rows.append(row)
    
    total_rows = len(rows)
    rows_per_folder = math.ceil(total_rows / num_folders)
    
    print(f"Total rows: {total_rows}")
    print(f"Splitting into {num_folders} folders (~{rows_per_folder} rows each)")
    
    os.makedirs(output_base, exist_ok=True)
    
    created_folders = []
    
    for i in range(num_folders):
        start_idx = i * rows_per_folder
        end_idx = min(start_idx + rows_per_folder, total_rows)
        folder_rows = rows[start_idx:end_idx]
        
        if not folder_rows:
            continue
        
        folder_name = f"part_{i+1:03d}"
        folder_path = os.path.join(output_base, folder_name)
        os.makedirs(folder_path, exist_ok=True)
        
        output_csv = os.path.join(folder_path, os.path.basename(csv_path))
        
        with open(output_csv, 'w', encoding='utf-8', newline='') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(folder_rows)
        
        created_folders.append((folder_name, folder_path, len(folder_rows)))
        print(f"  Created: {folder_name}/ ({len(folder_rows)} rows)")
    
    return created_folders, fieldnames


def create_processor_script(base_path, csv_filename):
    """Create the processor.py script in each folder."""
    processor_content = f'''#!/usr/bin/env python3
"""CSV Processor - auto-generated by split_and_run.py"""

import csv
import os
import sys

def process_file(input_path):
    """Process the CSV file."""
    folder = os.path.dirname(input_path) or '.'
    name = os.path.basename(folder)
    processed = 0
    errors = 0
    
    output_path = os.path.join(folder, 'processed.csv')
    
    print(f"[{{name}}] Starting processing...")
    print(f"[{{name}}] Input: {{input_path}}")
    
    if not os.path.exists(input_path):
        print(f"[{{name}}] Error: {{input_path}} not found!")
        sys.exit(1)
    
    with open(input_path, 'r', encoding='utf-8') as infile:
        reader = csv.DictReader(infile)
        
        with open(output_path, 'w', encoding='utf-8', newline='') as outfile:
            writer = csv.DictWriter(outfile, fieldnames=reader.fieldnames)
            writer.writeheader()
            
            for row in reader:
                # TODO: Add your processing logic here
                # Example: transform data, validate, aggregate, etc.
                
                processed += 1
                
                if processed % 100 == 0:
                    print(f"[{{name}}] Processed {{processed}} rows...")
                
                writer.writerow(row)
    
    print(f"[{{name}}] Done! Processed: {{processed}}, Errors: {{errors}}")

if __name__ == '__main__':
    folder = sys.argv[1] if len(sys.argv) > 1 else '.'
    input_file = os.path.join(folder, '{csv_filename}')
    process_file(input_file)
'''
    
    processor_path = os.path.join(base_path, 'processor.py')
    with open(processor_path, 'w', encoding='utf-8') as f:
        f.write(processor_content)
    os.chmod(processor_path, 0o755)


def create_procfile(base_path):
    """Create Procfile in the folder."""
    procfile_content = "process: python processor.py .\n"
    procfile_path = os.path.join(base_path, 'Procfile')
    with open(procfile_path, 'w') as f:
        f.write(procfile_content)


def create_master_procfile(output_base, folders):
    """Create a master Procfile that runs all processes."""
    procfile_content = ""
    for folder_name, folder_path, row_count in folders:
        procfile_content += f"{folder_name}: python processor.py .\n"
    
    procfile_path = os.path.join(output_base, 'Procfile')
    with open(procfile_path, 'w') as f:
        f.write(procfile_content)
    
    return procfile_path


def wait_for_user():
    """Wait for user to press Enter."""
    input("\n" + "=" * 50)
    input("Split complete! Press ENTER when ready to start processing...")
    input("(You can check folder contents in another terminal)")
    input("=" * 50 + "\n")


def start_pyrmind(procfile_path):
    """Start pyrmind with the Procfile."""
    print(f"\nStarting pyrmind with {procfile_path}...")
    print("Use 'pyrmind attach' in another terminal to monitor progress")
    print("Use 'pyrmind status' to check individual process status")
    print("-" * 50)
    
    os.chdir(os.path.dirname(procfile_path) or '.')
    
    try:
        subprocess.run(['pyrmind', 'start', '-f', os.path.basename(procfile_path), '--auto-restart'])
    except KeyboardInterrupt:
        print("\nInterrupted. Use 'pyrmind kill' to stop all processes.")


def main():
    parser = argparse.ArgumentParser(
        description='Split CSV into N folders and optionally run pyrmind to process in parallel'
    )
    parser.add_argument('--csv', help='Path to CSV file')
    parser.add_argument('--num-folders', type=int, help='Number of folders to split into')
    parser.add_argument('--output', default='processed', help='Output directory')
    parser.add_argument('--mode', choices=['1', '2', '3'], 
                       help='Mode: 1=interactive, 2=direct, 3=split only')
    args = parser.parse_args()
    
    # Get CSV file
    if args.csv and os.path.isfile(args.csv):
        csv_path = args.csv
    else:
        csv_path = select_csv_file()
    
    # Get number of folders
    if args.num_folders:
        num_folders = args.num_folders
    else:
        num_folders = select_num_folders()
    
    # Get output directory
    output_base = args.output if args.output else select_output_base()
    
    # Get mode
    if args.mode:
        mode = args.mode
    else:
        mode = select_mode()
    
    # Split CSV
    print(f"\nSplitting {csv_path} into {num_folders} folders...")
    folders, fieldnames = split_by_num_folders(csv_path, num_folders, output_base)
    
    csv_filename = os.path.basename(csv_path)
    
    # Create processor.py and Procfile in each folder
    print("\nCreating Procfile and processor.py in each folder...")
    for folder_name, folder_path, row_count in folders:
        create_processor_script(folder_path, csv_filename)
        create_procfile(folder_path)
        print(f"  {folder_name}/ Procfile, processor.py")
    
    # Create master Procfile
    master_procfile = create_master_procfile(output_base, folders)
    print(f"\nCreated master Procfile: {master_procfile}")
    
    # Summary
    total_rows = sum(count for _, _, count in folders)
    print("\n" + "=" * 50)
    print("SPLIT COMPLETE")
    print("=" * 50)
    print(f"Folders created: {len(folders)}")
    print(f"Total rows: {total_rows}")
    print(f"Output directory: {os.path.abspath(output_base)}")
    
    # Handle based on mode
    if mode == '1':
        wait_for_user()
        start_pyrmind(master_procfile)
    
    elif mode == '2':
        print("\nStarting pyrmind immediately...")
        start_pyrmind(master_procfile)
    
    else:
        print("\nTo start processing:")
        print(f"  cd {output_base}")
        print("  pyrmind start -f Procfile --auto-restart")
        print("\nTo monitor:")
        print("  pyrmind attach")


if __name__ == '__main__':
    main()
